# fly.preview.toml - Preview deployment configuration
#
# Use this config for preview deployments with: fly deploy --config fly.preview.toml
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'jst-dev-preview'
primary_region = 'arn'

[build]
  [build.args]
    GO_VERSION = '1.23.3'

[env]
  PORT = '8080'
  ENVIRONMENT = 'preview'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1 